### ISSUE TITLE
; changed to , in data

### ISSUE THREAD

**Issue by HynekPetrak** [icoxfog417/SAPExtractorDotNET#5]
Hi, the function below, makes ';' to be changed into ',', if the data contains ';' character. You split by either of those separators, but when assembling back, you put always ',' only.

 Dim separated As String() = Line.Split((LineSeparator + ItemSeparator).ToCharArray)
                Dim els As New List(Of String)

```
            For i As Integer = 0 To UBound(separated)
                Dim str As String = separated(i)
                If String.IsNullOrEmpty(str) Then Continue For
                If isElement(str) Then
                    els.Add(str)
                ElseIf isElement(els.Last + str) Then 'for data include separator
                    Dim concated As String = els.Last + ItemSeparator + str
                    els.RemoveAt(els.Count - 1)
                    els.Add(concated)
                End If

            Next
```

**Comment by icoxfog417** [comment]
I'll fix it as soon as possible. Thank you for [efficient blog post](http://scn.sap.com/community/interoperability-microsoft-net/blog/2014/09/11/downloading-a-sq01-or-sqvi-query-with-net-connector).

**Comment by HynekPetrak** [comment]
Hi, I believe the fix is not correct. You cannot use even regexp to parse the LDATA structure. Consider a field returned contains a text like 'aaa, 000: aaaa, 022: bbbb', which in the LDATA table will be represented as:
025:aaa, 000: aaaa, 022: bbbb;
, then the regexp will split into 3 substrings aaa, aaaa and bbbb, incorrectly.
Note the LDATA format does not escape separators ....

**Comment by icoxfog417** [comment]
@HynekPetrak , you are right.
And I recognized there is no smart way to split LDATA...(format is terrible).
