### ISSUE TITLE
get error when using sap loader

### ISSUE THREAD

**Issue by waleedmakarem** [icoxfog417/SAPExtractorDotNET#7]
first thanks for the tools, look great. But i get an error when trying to using SAPLoader. it seems that hte connection string into the sap.loader.configuation is wrong. how to get the ASHost ?

**Comment by icoxfog417** [comment]
Thank you for using the library.

You can confirm ASHost from SAP GUI. I think you can see SID , Group/Server and instance id in SAP GUI. Then,

* SID is `SYSID`
* Group/Server is `ASHOST`
* instance number is `SYSNR`

Below is the sample of the `SAP.Middleware.Connector` part of `saploader.exe.config`.

```
  <SAP.Middleware.Connector>
    <GeneralSettings defaultTraceLevel="1" traceDir="C:\Temp" traceEncoding="UTF-8" traceType="PROCESS" />

    <ClientSettings>
      <DestinationConfiguration>
        <destinations>
          <add NAME="MY_SAP" USER="xxxxx" PASSWD="xxxxx" CLIENT="xxx" LANG="xx" ASHOST="your Group/Server" SYSID="your SID" SYSNR="your instance number" POOL_SIZE="5" MAX_POOL_SIZE="10" />
        </destinations>
      </DestinationConfiguration>
    </ClientSettings>

  </SAP.Middleware.Connector>
```

**Comment by waleedmakarem** [comment]
Dear Sir, 
Seems connecting now. Thanks. I use the below command 
>>  saploader MY_SAP MARA exportfile.txt
Connect to SAP MY_SAP
One or more errors occured.

Why is this error.

**Comment by icoxfog417** [comment]
Could you show me the `dev_nco_rfc.log`? The error detail will be written in this file.
In my environment, above error does not occur. My SAP version is SAP ECC 6.0 and SAP BASIS is 731.

And please try to restrict the records or fields by option (`/f` and `/o`). Too many columns or records may cause error.

**Comment by waleedmakarem** [comment]
Really works :) .. Thanks so much. I can not imagine that I can extract data from SAP that fast. I extracted more than 30K records in less than 1.5 min. Thanks so much. 
One more issue, .. can i limit search by condition of one column , eg list all records that has column X with value Y.
Thanks so much for your support. Really appreciated.

**Comment by icoxfog417** [comment]
It’s my pleasure!
Of course you can limit the records by `/o` option. Please see the [Example](https://github.com/icoxfog417/SAPExtractorDotNET/tree/master/saploader#examples). It restricts the records by `BUKRS=1*` (company codes which start with `1`).

**Comment by waleedmakarem** [comment]
on issue. How can I setup login credentials as standalone , ie not from the saploader.exe.config. I need to update : Dim connection As RfcDestination = connector.Login

**Comment by waleedmakarem** [comment]
can i use the tool to extract tables names ?

**Comment by icoxfog417** [comment]
The table `DD02L` stores table names. So I think that you can extract table names from it.

**Comment by waleedmakarem** [comment]
it works for one system ,but for another , I get Not_Authorized message after  connecting to SAP. I can use the other system to display date. I assume that I should be authorized to this system

**Comment by icoxfog417** [comment]
I think you can deal with multiple SAP system by setting multiple destination in `destinations` section of `saploader.exe.config.`.

**Comment by waleedmakarem** [comment]
I get strange issue, when downlading data, that was working before.. I get error "String is not in the correct format ". data download was working pretty well before. I tried to run it again, it it appears in 95 % of trials, and sometime data download is ok. I select specific fields  to make download easier.

**Comment by waleedmakarem** [comment]
I get strange issue, when downlading data, that was working before.. I get error "String is not in the correct format ". data download was working pretty well before. I tried to run it again, it it appears in 95 % of trials, and sometime data download is ok. I select specific fields  to make download easier.

**Comment by waleedmakarem** [comment]
now above issue works about in 50 % of cases. Are there in any issue, , or work around to mitigate ?
Thanks again for your magic tools. it really saved my much time.

**Comment by icoxfog417** [comment]
Thank you for reporting. If you can reproduce the error, please raise new issue.  
This issue became a little long, so I close it.
