### ISSUE TITLE
builds break can you include connector

### ISSUE THREAD

**Issue by patagoniahiker** [icoxfog417/SAPExtractorDotNET#8]
Hi I cannot get the dll's says I need to be a partner, i am just a developer. Can you please include the dll's and check the build

**Comment by icoxfog417** [comment]
I'm sorry for the lacking of dll, but SAP forbids the redistribution of the library.

Below is the full text of the license for every conector of SAP (you can see it [here](https://websmp101.sap-ag.de/~form/handler?_APP=00200682500000002672&_EVENT=DISPLAY&_SCENARIO=&_HIER_KEY=501100035870000018527&_HIER_KEY=601100035870000233098&)).

## License terms for SAP Connectors

The following license terms apply to all SAP Connectors for RFC communication, in particular: SAP Business Connector, SAP Java Connector (JCo), SAP Connector for Microsoft .NET (NCo), RFC Library and NetWeaver RFC Library.
- All SAP Connectors are licensed without additional license fees as part of the respective solution or component license. However, please note that each connector may be used only for connecting external (non-SAP) applications to SAP Systems/SAP Solutions. Scenarios, in which two external (non-SAP) applications are integrated via an SAP Connector, are not allowed.
- The redistribution of any connector is not allowed.
- All SAP users accessing application functionality through the relevant connector are required to be licensed under a respective solution or component license.

Here you find the answers to [frequently asked questions](https://websmp101.sap-ag.de/~form/sapnet?_SHORTKEY=01100035870000765680) about the license conditions for all SAP Connectors.
